# Generated by Django 4.0.5 on 2022-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_unique_id_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='local_currency',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
