# Generated by Django 4.0.5 on 2022-06-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='total_deposit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_withdraw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
