# Generated by Django 4.0.5 on 2022-06-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_total_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
