# Generated by Django 4.0.5 on 2022-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bankdetails_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ty_pe', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tr_ref', models.CharField(max_length=20)),
                ('sell_date', models.DateTimeField()),
                ('sysmbol', models.CharField(max_length=100)),
                ('duration_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('barrier', models.CharField(max_length=100)),
                ('barrier_sec', models.CharField(blank=True, max_length=100, null=True)),
                ('stake', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
