# Generated by Django 4.0.5 on 2022-06-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_contract_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='duration_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='duration_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
