# Generated by Django 4.0.5 on 2022-06-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_contract_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ty_pe_sub',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
