# Generated by Django 4.0.5 on 2022-07-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contract_ty_pe_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payout',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='payout_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='stake_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
