# Generated by Django 4.0.5 on 2022-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contract_payout_contract_payout_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
