# Generated by Django 4.0.5 on 2022-06-28 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_amount', models.IntegerField(default=5)),
                ('max_amount', models.IntegerField(default=2000)),
                ('website', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('tel', models.CharField(max_length=50)),
                ('tex', models.TextField(blank=True, null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
